services:
  web:
    restart: always
    build: .
    container_name: care_mate_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: care_mate_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
